# Generated by Django 4.2.6 on 2023-10-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('ratings', models.JSONField()),
                ('top_tags', models.CharField(max_length=255)),
                ('courses', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('helpful', models.IntegerField()),
                ('not_helpful', models.IntegerField()),
                ('take_again', models.BooleanField()),
                ('for_credit', models.BooleanField()),
                ('has_textbook', models.BooleanField()),
                ('attendance_mandatory', models.BooleanField()),
                ('grade', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='professor.professor')),
            ],
        ),
    ]
