# Generated by Django 4.2.6 on 2023-10-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_rmp_url_alter_review_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='courses',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='ratings',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='top_tags',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
