# Generated by Django 4.2.6 on 2023-10-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_alter_professor_courses_alter_professor_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='attendance_mandatory',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='for_credit',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='has_textbook',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='take_again',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
